// Registry that maps a template kind to its (auto-generated) file list.
// Per-kind data lives in templateFiles.<kind>.ts (generated by scripts/extract-templates.mjs).

export interface TemplateFile {
    path: string;
    content: string;
    binary?: boolean;
    copyOnly?: boolean;
    /** Conditions under which this file is EXCLUDED (from template.json modifiers) */
    excludeConditions?: string[];
}

import { templateFiles as shinyappFiles } from './templateFiles.shinyapp';
import { templateFiles as shinyaspnetFiles } from './templateFiles.shinyaspnet';
import { templateFiles as shinyblazorFiles } from './templateFiles.shinyblazor';

export type TemplateKind = 'shinyapp' | 'shinyaspnet' | 'shinyblazor';

export const templateFilesByKind: Record<TemplateKind, TemplateFile[]> = {
    shinyapp: shinyappFiles,
    shinyaspnet: shinyaspnetFiles,
    shinyblazor: shinyblazorFiles,
};

/** sourceName used in each template — the literal string we replace with the user's project name. */
export const templateSourceName: Record<TemplateKind, string> = {
    shinyapp: 'ShinyApp',
    shinyaspnet: 'ShinyAspNet',
    shinyblazor: 'ShinyBlazor',
};
