// Port of tools/ShinyThemeGen/Emitter.cs — produces the same CSS / MAUI C# / theme JSON.

import { buildScheme, palettesFromSeeds } from './scheme';
import { SHAPE, BORDER, DENSITY, STATE, SPACING, TYPE, ELEVATION, MAUI_SHADOW, DEFAULT_MONO_STACK, kebab, type Seeds } from './tokens';

const AUTOGEN_CS =
    '// <auto-generated>\n' +
    '// Generated by tools/ShinyThemeGen from /themes/*.json. DO NOT EDIT.\n' +
    '// Edit the source JSON theme and re-run: dotnet run --project tools/ShinyThemeGen\n' +
    '// </auto-generated>';

const AUTOGEN_CSS =
    '/* <auto-generated>\n' +
    '   Generated by tools/ShinyThemeGen from /themes/*.json. DO NOT EDIT.\n' +
    '   Edit the source JSON theme and re-run: dotnet run --project tools/ShinyThemeGen\n' +
    '   </auto-generated> */';

function fmt(v: number): string {
    return v.toFixed(4).replace(/\.?0+$/, '');
}
function px(v: number): string {
    return v === 0 ? '0px' : fmt(v) + 'px';
}

function safeIdent(name: string): string {
    const parts = name.split(/[^A-Za-z0-9]+/).filter(Boolean);
    let id = parts.map((p) => p[0].toUpperCase() + p.slice(1)).join('');
    if (!id || !/^[A-Za-z_]/.test(id)) id = 'Custom' + id;
    return id;
}

export interface ThemeData {
    name: string;
    slug: string;
    description: string;
    seeds: Seeds;
    light: [string, string][];
    dark: [string, string][];
    shape: [string, number][];
}

export function buildThemeData(name: string, slug: string, description: string, seeds: Seeds): ThemeData {
    const p = palettesFromSeeds(seeds);
    return {
        name,
        slug,
        description,
        seeds,
        light: buildScheme(p, false),
        dark: buildScheme(p, true),
        shape: SHAPE.map(([n, v]) => [n, v] as [string, number]),
    };
}

// ============================================================ Blazor CSS

export function emitCss(t: ThemeData): string {
    let sb = AUTOGEN_CSS + '\n\n';

    sb += ':root {\n';
    sb += '    /* ===== Color (light) ===== */\n';
    for (const [role, hex] of t.light) sb += `    --shiny-color-${kebab(role)}: ${hex};\n`;

    sb += '\n    /* ===== Shape ===== */\n';
    for (const [name, val] of t.shape) sb += `    --shiny-shape-${kebab(name)}: ${px(val)};\n`;

    sb += '\n    /* ===== Border widths ===== */\n';
    for (const [name, val] of BORDER) sb += `    --shiny-border-${kebab(name)}: ${px(val)};\n`;

    sb += '\n    /* ===== State ===== */\n';
    for (const [name, val] of STATE) sb += `    --shiny-state-${kebab(name)}: ${fmt(val)};\n`;

    sb += '\n    /* ===== Density ===== */\n';
    // The scale is a bare multiplier for calc(); every other density token is a measurement.
    for (const [name, val] of DENSITY)
        sb += `    --shiny-density-${kebab(name)}: ${name === 'Scale' ? fmt(val) : px(val)};\n`;

    sb += '\n    /* ===== Spacing ===== */\n';
    for (const [name, val] of SPACING) sb += `    --shiny-spacing-${name.replace('Space', '')}: ${px(val)};\n`;

    sb += '\n    /* ===== Type scale ===== */\n';
    // The creator does not yet edit typography, so these carry the shared defaults: the body family
    // inherits the host app's font, and the off-scale multiplier is 1.
    sb += '    --shiny-type-font-family: inherit;\n';
    sb += '    --shiny-type-font-family-display: var(--shiny-type-font-family);\n';
    sb += `    --shiny-type-font-family-mono: ${DEFAULT_MONO_STACK};\n`;
    sb += '    --shiny-type-scale: 1;\n';
    for (const [role, size, lh, weight, tracking] of TYPE) {
        const k = kebab(role);
        sb += `    --shiny-type-${k}-size: ${px(size)};\n`;
        sb += `    --shiny-type-${k}-line-height: ${px(lh)};\n`;
        sb += `    --shiny-type-${k}-weight: ${weight};\n`;
        sb += `    --shiny-type-${k}-tracking: ${px(tracking)};\n`;
    }

    sb += '\n    /* ===== Elevation ===== */\n';
    for (const [name, shadow] of ELEVATION) sb += `    --shiny-elevation-${name.replace('Level', '')}: ${shadow};\n`;

    sb += '}\n\n';

    sb += '/* Explicit dark mode (toggle .shiny-theme-dark on <html> or a container) */\n';
    sb += ':root.shiny-theme-dark,\n.shiny-theme-dark {\n';
    for (const [role, hex] of t.dark) sb += `    --shiny-color-${kebab(role)}: ${hex};\n`;
    sb += '}\n\n';

    sb += '/* Follow OS dark preference unless explicitly set to light */\n';
    sb += '@media (prefers-color-scheme: dark) {\n';
    sb += '    :root:not(.shiny-theme-light) {\n';
    for (const [role, hex] of t.dark) sb += `        --shiny-color-${kebab(role)}: ${hex};\n`;
    sb += '    }\n}\n';

    return sb;
}

// ============================================================ MAUI ResourceDictionaries

export function emitMauiDictionary(t: ThemeData, dark: boolean): string {
    const ident = safeIdent(t.name);
    const className = `${ident}${dark ? 'Dark' : 'Light'}Theme`;
    const roles = dark ? t.dark : t.light;

    let sb = AUTOGEN_CS + '\n\n';
    sb += 'using Microsoft.Maui;\n';
    sb += 'using Microsoft.Maui.Controls;\n';
    sb += 'using Microsoft.Maui.Graphics;\n\n';
    sb += 'namespace Shiny.Maui.Controls.Themes;\n\n';
    sb += `/// <summary>${t.name} theme — ${dark ? 'dark' : 'light'} scheme resource dictionary.</summary>\n`;
    sb += `public partial class ${className} : ResourceDictionary\n{\n`;
    sb += `    public ${className}()\n    {\n`;

    sb += '        // ===== Color =====\n';
    for (const [role, hex] of roles) sb += `        this.Add(ShinyThemeKeys.Color.${role}, Color.FromArgb("${hex}"));\n`;

    sb += '\n        // ===== Shape =====\n';
    for (const [name, val] of t.shape) {
        sb += `        this.Add(ShinyThemeKeys.Shape.${name}, ${fmt(val)}d);\n`;
        // CornerRadius twin: StrokeShape/RoundRectangle properties are typed CornerRadius, and a
        // dynamic resource is assigned verbatim with no conversion, so a double would be dropped.
        sb += `        this.Add(ShinyThemeKeys.Shape.${name}Radius, new CornerRadius(${fmt(val)}d));\n`;
    }

    sb += '\n        // ===== Border =====\n';
    for (const [name, val] of BORDER) sb += `        this.Add(ShinyThemeKeys.Border.${name}, ${fmt(val)}d);\n`;

    sb += '\n        // ===== State =====\n';
    for (const [name, val] of STATE) sb += `        this.Add(ShinyThemeKeys.State.${name}, ${fmt(val)}d);\n`;

    sb += '\n        // ===== Density =====\n';
    for (const [name, val] of DENSITY) sb += `        this.Add(ShinyThemeKeys.Density.${name}, ${fmt(val)}d);\n`;

    sb += '\n        // ===== Spacing =====\n';
    for (const [name, val] of SPACING) sb += `        this.Add(ShinyThemeKeys.Spacing.${name}, ${fmt(val)}d);\n`;

    sb += '\n        // ===== Type =====\n';
    sb += '        this.Add(ShinyThemeKeys.Type.FontFamily, "");\n';
    sb += '        this.Add(ShinyThemeKeys.Type.FontFamilyDisplay, "");\n';
    sb += '        this.Add(ShinyThemeKeys.Type.FontFamilyMono, "");\n';
    sb += '        this.Add(ShinyThemeKeys.Type.Scale, 1d);\n';
    for (const [role, size, , weight] of TYPE) {
        sb += `        this.Add(ShinyThemeKeys.Type.${role}Size, ${fmt(size)}d);\n`;
        // MAUI has no numeric weight on Label, so the scale's weights become the one distinction the
        // platform can actually express.
        sb += `        this.Add(ShinyThemeKeys.Type.${role}Attributes, FontAttributes.${weight >= 600 ? 'Bold' : 'None'});\n`;
    }

    sb += '\n        // ===== Elevation =====\n';
    const shadowHex = roles.find(([role]) => role === 'Shadow')?.[1] ?? '#000000';
    for (const [name, ox, oy, radius, opacity] of MAUI_SHADOW)
        sb += `        this.Add(ShinyThemeKeys.Elevation.${name}, new Shadow { Brush = new SolidColorBrush(Color.FromArgb("${shadowHex}")), Offset = new Point(${fmt(ox)}d, ${fmt(oy)}d), Radius = ${fmt(radius)}f, Opacity = ${fmt(opacity)}f });\n`;

    sb += '    }\n}\n';
    return sb;
}

export function emitMauiTheme(t: ThemeData): string {
    const ident = safeIdent(t.name);
    let sb = AUTOGEN_CS + '\n\n';
    sb += 'using Microsoft.Maui.Controls;\n\n';
    sb += 'namespace Shiny.Maui.Controls.Themes;\n\n';
    sb += `/// <summary>${t.description}</summary>\n`;
    sb += `public sealed class ${ident}Theme : IShinyTheme\n{\n`;
    sb += `    public string Name => "${t.name}";\n`;
    sb += `    public ResourceDictionary Light { get; } = new ${ident}LightTheme();\n`;
    sb += `    public ResourceDictionary Dark { get; } = new ${ident}DarkTheme();\n`;
    sb += '}\n';
    return sb;
}

// ============================================================ Theme JSON (source of truth)

export function emitJson(t: ThemeData): string {
    const obj = {
        $schema: './shiny-theme.schema.json',
        name: t.name,
        slug: t.slug,
        description: t.description,
        seeds: t.seeds,
    };
    return JSON.stringify(obj, null, 4) + '\n';
}

// ============================================================ File manifest

/** A single generated artifact, ready to preview, copy, or write into the zip. */
export interface ThemeFile {
    /** Path inside the generated zip, e.g. "maui/OceanTheme.cs". */
    path: string;
    /** File name on its own — used for single-file downloads and tab labels. */
    fileName: string;
    /** Prism language id for the preview. */
    language: 'json' | 'css' | 'csharp' | 'markdown';
    /** Short line explaining where the file belongs. */
    hint: string;
    content: string;
}

export interface ThemePlatform {
    id: string;
    label: string;
    /** Rendered above the file tabs. */
    blurb: string;
    files: ThemeFile[];
}

export function emitReadme(t: ThemeData): string {
    const ident = safeIdent(t.name);
    return (
        `# ${t.name}\n\n` +
        `${t.description}\n\n` +
        'Generated with the [Shiny Theme Creator](https://www.shinylib.net/controls/theming/creator/).\n' +
        'The output is byte-identical to running `dotnet run --project tools/ShinyThemeGen` against the theme JSON.\n\n' +
        '## Seeds\n\n' +
        '| Role | Hex |\n| --- | --- |\n' +
        Object.entries(t.seeds).map(([k, v]) => `| ${k} | \`${v}\` |`).join('\n') +
        '\n\n## Files\n\n' +
        `- \`themes/${t.slug}.json\` — the source of truth. Drop it into \`/themes/\` in your fork of the\n` +
        '  controls repo and run `dotnet run --project tools/ShinyThemeGen` to regenerate both platforms.\n' +
        `- \`blazor/shiny-theme-${t.slug}.css\` — ship as a static asset and \`<link>\` it **after** the core\n` +
        '  `shiny-theme.css`. Toggle `.shiny-theme-dark` / `.shiny-theme-light` on `<html>` to force a scheme;\n' +
        '  otherwise it follows the OS preference.\n' +
        `- \`maui/${ident}Theme.cs\`, \`maui/${ident}LightTheme.cs\`, \`maui/${ident}DarkTheme.cs\` — add to your\n` +
        '  MAUI project and register it:\n\n' +
        '```csharp\n' +
        'builder.UseShinyControls(cfg => cfg.UseTheme(new ' + ident + 'Theme()));\n' +
        '```\n'
    );
}

/** Everything the creator can hand you, grouped by the platform it targets. */
export function buildThemeFiles(t: ThemeData): ThemePlatform[] {
    const ident = safeIdent(t.name);
    return [
        {
            id: 'json',
            label: 'Theme JSON',
            blurb: 'The source of truth — everything else is generated from these seeds.',
            files: [
                {
                    path: `themes/${t.slug}.json`,
                    fileName: `${t.slug}.json`,
                    language: 'json',
                    hint: 'Drop into /themes/ and run the ShinyThemeGen tool to regenerate both platforms.',
                    content: emitJson(t),
                },
            ],
        },
        {
            id: 'blazor',
            label: 'Blazor',
            blurb: 'CSS custom properties for both schemes, plus an OS dark-preference fallback.',
            files: [
                {
                    path: `blazor/shiny-theme-${t.slug}.css`,
                    fileName: `shiny-theme-${t.slug}.css`,
                    language: 'css',
                    hint: 'Ship as a static asset and link it after the core shiny-theme.css.',
                    content: emitCss(t),
                },
            ],
        },
        {
            id: 'maui',
            label: '.NET MAUI',
            blurb: `Register with UseShinyControls(cfg => cfg.UseTheme(new ${ident}Theme())).`,
            files: [
                {
                    path: `maui/${ident}Theme.cs`,
                    fileName: `${ident}Theme.cs`,
                    language: 'csharp',
                    hint: 'The IShinyTheme entry point pairing the light and dark dictionaries.',
                    content: emitMauiTheme(t),
                },
                {
                    path: `maui/${ident}LightTheme.cs`,
                    fileName: `${ident}LightTheme.cs`,
                    language: 'csharp',
                    hint: 'ResourceDictionary for the light scheme.',
                    content: emitMauiDictionary(t, false),
                },
                {
                    path: `maui/${ident}DarkTheme.cs`,
                    fileName: `${ident}DarkTheme.cs`,
                    language: 'csharp',
                    hint: 'ResourceDictionary for the dark scheme.',
                    content: emitMauiDictionary(t, true),
                },
            ],
        },
        {
            id: 'readme',
            label: 'README',
            blurb: 'Wiring instructions, shipped in the zip alongside the generated files.',
            files: [
                {
                    path: 'README.md',
                    fileName: 'README.md',
                    language: 'markdown',
                    hint: 'Included at the root of the downloaded zip.',
                    content: emitReadme(t),
                },
            ],
        },
    ];
}
