// Port of tools/ShinyThemeGen/Emitter.cs — produces the same CSS / MAUI C# / theme JSON.

import { buildScheme, palettesFromSeeds } from './scheme';
import { SHAPE, STATE, SPACING, TYPE, ELEVATION, MAUI_SHADOW, kebab, type Seeds } from './tokens';

const AUTOGEN_CS =
    '// <auto-generated>\n' +
    '// Generated by tools/ShinyThemeGen from /themes/*.json. DO NOT EDIT.\n' +
    '// Edit the source JSON theme and re-run: dotnet run --project tools/ShinyThemeGen\n' +
    '// </auto-generated>';

const AUTOGEN_CSS =
    '/* <auto-generated>\n' +
    '   Generated by tools/ShinyThemeGen from /themes/*.json. DO NOT EDIT.\n' +
    '   Edit the source JSON theme and re-run: dotnet run --project tools/ShinyThemeGen\n' +
    '   </auto-generated> */';

function fmt(v: number): string {
    return v.toFixed(4).replace(/\.?0+$/, '');
}
function px(v: number): string {
    return v === 0 ? '0px' : fmt(v) + 'px';
}

function safeIdent(name: string): string {
    const parts = name.split(/[^A-Za-z0-9]+/).filter(Boolean);
    let id = parts.map((p) => p[0].toUpperCase() + p.slice(1)).join('');
    if (!id || !/^[A-Za-z_]/.test(id)) id = 'Custom' + id;
    return id;
}

export interface ThemeData {
    name: string;
    slug: string;
    description: string;
    seeds: Seeds;
    light: [string, string][];
    dark: [string, string][];
    shape: [string, number][];
}

export function buildThemeData(name: string, slug: string, description: string, seeds: Seeds): ThemeData {
    const p = palettesFromSeeds(seeds);
    return {
        name,
        slug,
        description,
        seeds,
        light: buildScheme(p, false),
        dark: buildScheme(p, true),
        shape: SHAPE.map(([n, v]) => [n, v] as [string, number]),
    };
}

// ============================================================ Blazor CSS

export function emitCss(t: ThemeData): string {
    let sb = AUTOGEN_CSS + '\n\n';

    sb += ':root {\n';
    sb += '    /* ===== Color (light) ===== */\n';
    for (const [role, hex] of t.light) sb += `    --shiny-color-${kebab(role)}: ${hex};\n`;

    sb += '\n    /* ===== Shape ===== */\n';
    for (const [name, val] of t.shape) sb += `    --shiny-shape-${kebab(name)}: ${px(val)};\n`;

    sb += '\n    /* ===== State ===== */\n';
    for (const [name, val] of STATE) sb += `    --shiny-state-${kebab(name)}: ${fmt(val)};\n`;

    sb += '\n    /* ===== Spacing ===== */\n';
    for (const [name, val] of SPACING) sb += `    --shiny-spacing-${name.replace('Space', '')}: ${px(val)};\n`;

    sb += '\n    /* ===== Type scale ===== */\n';
    for (const [role, size, lh, weight, tracking] of TYPE) {
        const k = kebab(role);
        sb += `    --shiny-type-${k}-size: ${px(size)};\n`;
        sb += `    --shiny-type-${k}-line-height: ${px(lh)};\n`;
        sb += `    --shiny-type-${k}-weight: ${weight};\n`;
        sb += `    --shiny-type-${k}-tracking: ${px(tracking)};\n`;
    }

    sb += '\n    /* ===== Elevation ===== */\n';
    for (const [name, shadow] of ELEVATION) sb += `    --shiny-elevation-${name.replace('Level', '')}: ${shadow};\n`;

    sb += '}\n\n';

    sb += '/* Explicit dark mode (toggle .shiny-theme-dark on <html> or a container) */\n';
    sb += ':root.shiny-theme-dark,\n.shiny-theme-dark {\n';
    for (const [role, hex] of t.dark) sb += `    --shiny-color-${kebab(role)}: ${hex};\n`;
    sb += '}\n\n';

    sb += '/* Follow OS dark preference unless explicitly set to light */\n';
    sb += '@media (prefers-color-scheme: dark) {\n';
    sb += '    :root:not(.shiny-theme-light) {\n';
    for (const [role, hex] of t.dark) sb += `        --shiny-color-${kebab(role)}: ${hex};\n`;
    sb += '    }\n}\n';

    return sb;
}

// ============================================================ MAUI ResourceDictionaries

export function emitMauiDictionary(t: ThemeData, dark: boolean): string {
    const ident = safeIdent(t.name);
    const className = `${ident}${dark ? 'Dark' : 'Light'}Theme`;
    const roles = dark ? t.dark : t.light;

    let sb = AUTOGEN_CS + '\n\n';
    sb += 'using Microsoft.Maui;\n';
    sb += 'using Microsoft.Maui.Controls;\n';
    sb += 'using Microsoft.Maui.Graphics;\n\n';
    sb += 'namespace Shiny.Maui.Controls.Themes;\n\n';
    sb += `/// <summary>${t.name} theme — ${dark ? 'dark' : 'light'} scheme resource dictionary.</summary>\n`;
    sb += `public partial class ${className} : ResourceDictionary\n{\n`;
    sb += `    public ${className}()\n    {\n`;

    sb += '        // ===== Color =====\n';
    for (const [role, hex] of roles) sb += `        this.Add(ShinyThemeKeys.Color.${role}, Color.FromArgb("${hex}"));\n`;

    sb += '\n        // ===== Shape =====\n';
    for (const [name, val] of t.shape) sb += `        this.Add(ShinyThemeKeys.Shape.${name}, ${fmt(val)}d);\n`;

    sb += '\n        // ===== State =====\n';
    for (const [name, val] of STATE) sb += `        this.Add(ShinyThemeKeys.State.${name}, ${fmt(val)}d);\n`;

    sb += '\n        // ===== Spacing =====\n';
    for (const [name, val] of SPACING) sb += `        this.Add(ShinyThemeKeys.Spacing.${name}, ${fmt(val)}d);\n`;

    sb += '\n        // ===== Type sizes =====\n';
    for (const [role, size] of TYPE) sb += `        this.Add(ShinyThemeKeys.Type.${role}Size, ${fmt(size)}d);\n`;

    sb += '\n        // ===== Elevation =====\n';
    for (const [name, ox, oy, radius, opacity] of MAUI_SHADOW)
        sb += `        this.Add(ShinyThemeKeys.Elevation.${name}, new Shadow { Brush = new SolidColorBrush(Colors.Black), Offset = new Point(${fmt(ox)}d, ${fmt(oy)}d), Radius = ${fmt(radius)}f, Opacity = ${fmt(opacity)}f });\n`;

    sb += '    }\n}\n';
    return sb;
}

export function emitMauiTheme(t: ThemeData): string {
    const ident = safeIdent(t.name);
    let sb = AUTOGEN_CS + '\n\n';
    sb += 'using Microsoft.Maui.Controls;\n\n';
    sb += 'namespace Shiny.Maui.Controls.Themes;\n\n';
    sb += `/// <summary>${t.description}</summary>\n`;
    sb += `public sealed class ${ident}Theme : IShinyTheme\n{\n`;
    sb += `    public string Name => "${t.name}";\n`;
    sb += `    public ResourceDictionary Light { get; } = new ${ident}LightTheme();\n`;
    sb += `    public ResourceDictionary Dark { get; } = new ${ident}DarkTheme();\n`;
    sb += '}\n';
    return sb;
}

// ============================================================ Theme JSON (source of truth)

export function emitJson(t: ThemeData): string {
    const obj = {
        $schema: './shiny-theme.schema.json',
        name: t.name,
        slug: t.slug,
        description: t.description,
        seeds: t.seeds,
    };
    return JSON.stringify(obj, null, 4) + '\n';
}
